version: '2'

services:
  consul:
    image: consul:latest
    command: consul agent -config-file=/consul/config/consul.json
    volumes:
      - ./data/:/consul/data/
      - ./config/:/consul/config/
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  api:
    image: orleans-sample-api
    ports:
     - "8080:80"
    build:
      context: ../Src
      dockerfile: ../src/Orleans.Sample.Api/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  silo:
    image: orleans-sample-silo
    ports:
      - "1111:1111"
    build:
      context: ../Src
      dockerfile: ../src/Orleans.Sample.Silo/dockerfile
    environment:
      - ENVIRONMENT=Development
volumes:
  consul_data:
    driver: local