FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base

RUN apt update && \
    apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore -s "https://api.nuget.org/v3/index.json" "Orleans.Sample.Silo/Orleans.Sample.Silo.csproj"
RUN dotnet build "Orleans.Sample.Silo/Orleans.Sample.Silo.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Orleans.Sample.Silo/Orleans.Sample.Silo.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Orleans.Sample.Silo.dll"]
